spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    # Either include URI in config.import property, or specify as cloud.config.uri
    # import: "optional:configserver:"
    import: "configserver:http://configserver:8071"
  # cloud:
  #   config:
  #     uri: "http://configserver:8071"
