spring:
  application:
    name: eureka-server

  cloud:
    config:
#      uri: "http://configserver:8071"
        uri: "http://localhost:8071"

  config:
    import: "configserver:"

  output:
    ansi:
      enabled: always
