server:
  port: 8072

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
  instance:
    preferIpAddress: true

spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
      - id: organization-service
        uri: lb://organization-service
        predicates:
        - Path=/org/**
        filters:
        - RewritePath=/org/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: "*"
