server:
  port: 8072

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
  instance:
    preferIpAddress: true

spring:
  cloud:
    gateway:
#      discovery.locator:
#        enabled: true
#        lowerCaseServiceId: true
      routes:
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
            - Path=/license/**
          filters:
            - RewritePath=/license/(?<path>.*), /$\{path}
#            - RemoveRequestHeader=Cookie,Set-Cookie  # remove sensitive headers, doesn't happen automatically
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
#            - RemoveRequestHeader=Cookie,Set-Cookie  # remove sensitive headers, doesn't happen automatically

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.optimagrowth: DEBUG