server:
  port: 8081

spring:
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  cloud:
    stream:
      source: simpleSourceBean
      bindings:
        simpleSourceBean-out-0:
          destination: orgChangeTopic
          content-type: application/json
      kafka:
        binder:
          zkNodes:
            - kafka
          brokers:
            - kafka

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

logging:
  level:
    com.optimagrowth: DEBUG
